version: "3.9"
services:
  app:
    image: 31081991/aa-app
    container_name: app
    restart: always
    ports:
      - '80:4200'
    depends_on:
      - db
  db:
    image: 31081991/aa-db
    container_name: db
    restart: always
    ports: 
      - "3000:3000"